site_name: MRFI documention

nav:
- Index: index.md
- Documents:
  - core.md
  - selector.md
  - quantization.md
  - error_mode.md
  - observer.md
- Examples:
  - basic_observe.md

theme:
  name: "material"
  palette:
    - scheme: default
      primary: brown
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, "..")
          options:
            heading_level: 3
            members_order: "source"
            merge_init_into_class: True
