FI_activation: false
FI_enable: false
FI_weight: true
flip_mode: flip_int_highest
flip_mode_args:
  bit_width: 8
layerwise_quantization:
  bit_width: 8
  dynamic_range: auto
observer:
  map: mse
  reduce: sum
selector: RandomPositionSelector_FixN
selector_args:
  n: 1
sub_modules:
  conv1:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 1
    observer:
      map: mse
      reduce: sum
  conv2:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
    observer:
      map: mse
      reduce: sum
  conv3:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
    observer:
      map: mse
      reduce: sum
  conv4:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
    observer:
      map: mse
      reduce: sum
  conv5:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
    observer:
      map: mse
      reduce: sum
  conv6:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
    observer:
      map: mse
      reduce: sum
  globalavgpool:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
