FI_activation: false
FI_enable: false
FI_weight: false
flip_mode: set_value
flip_mode_args:
  value: 100 
observer:
  map: custom
  reduce: sum
selector: RandomPositionSelector_FixN
selector_args:
  n: 1
sub_modules:
  conv1:
    FI_enable: true
    observer:
      map: custom
      reduce: sum
  conv2:
    FI_enable: false
    observer:
      map: custom
      reduce: sum
  conv3:
    FI_enable: false
    observer:
      map: custom
      reduce: sum
  conv4:
    FI_enable: false
    observer:
      map: custom
      reduce: sum
  conv5:
    FI_enable: false
    observer:
      map: custom
      reduce: sum
  conv6:
    FI_enable: false
    observer:
      map: custom
      reduce: sum
  globalavgpool:
    FI_enable: false
    observer:
      map: custom
      reduce: sum
