FI_activation: true
FI_enable: true
FI_weight: false
flip_mode: flip_int_highest
flip_mode_args:
  bit_width: 8
layerwise_quantization:
  bit_width: 8
  dynamic_range: auto
observer:
  map: mse
  reduce: sum
selector: RandomPositionSelector_Rate
selector_args:
  poisson: true
  rate: 0.001
sub_modules:
  conv1:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 1
  bn11:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
  conv2:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
  bn12:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
  conv3:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
  bn21:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
  conv4:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
  bn22:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
  conv5:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
  bn31:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
  conv6:
    layerwise_quantization:
      bit_width: 8
      dynamic_range: 8
  bn32:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
  globalavgpool:
    FI_enable: false
    observer:
      map: mse
      reduce: sum
